-- V1 baseline — 2026-06-11 라이브 스키마(pg_dump) 스냅샷.
-- 기존 운영 DB 에서는 실행되지 않고(baseline-on-migrate 로 "이미 적용됨" 처리),
-- 신규 설치(빈 DB)에서만 실행되어 전체 스키마를 만든다.
-- 이후 모든 스키마 변경은 V2, V3 … 마이그레이션 파일로만 한다 (ddl-auto=validate 가 드리프트를 기동 시점에 차단).

CREATE TABLE intent_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    error_detail TEXT,
    error_type VARCHAR(255) NOT NULL,
    failed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    raw_input TEXT,
    slack_channel VARCHAR(255),
    slack_user_id VARCHAR(255)
);

CREATE TABLE issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignee VARCHAR(255),
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    description TEXT,
    issue_key VARCHAR(255) NOT NULL,
    issue_type VARCHAR(255),
    jira_created TIMESTAMP(6) WITH TIME ZONE,
    jira_updated TIMESTAMP(6) WITH TIME ZONE,
    parent_key VARCHAR(255),
    reporter VARCHAR(255),
    slack_channel VARCHAR(255),
    slack_thread_ts VARCHAR(255),
    sprint_id INTEGER,
    sprint_name VARCHAR(255),
    status VARCHAR(255),
    status_category VARCHAR(255),
    story_point DOUBLE PRECISION,
    subtask BOOLEAN NOT NULL,
    summary VARCHAR(255) NOT NULL,
    synced_at TIMESTAMP(6) WITH TIME ZONE,
    in_progress_since TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_issues_issue_key UNIQUE (issue_key)
);

CREATE TABLE processed_jira_changelog (
    changelog_id VARCHAR(64) PRIMARY KEY,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE user_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jira_account_id VARCHAR(255),
    jira_display_name VARCHAR(255) NOT NULL,
    slack_display_name VARCHAR(255),
    slack_user_id VARCHAR(255) NOT NULL,
    reminder_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    assign_dm_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT uk_user_mappings_slack_user_id UNIQUE (slack_user_id)
);

CREATE INDEX idx_issues_status_category ON issues (status_category);
CREATE INDEX idx_issues_sprint_id ON issues (sprint_id);
CREATE INDEX idx_issues_completed_at ON issues (completed_at);
