-- v0.0.29: Slack 요청 → 봇 응답까지의 소요시간 계측 (원인 파악/최적화 근거 데이터)
-- total_ms = Slack 메시지 ts 기준 end-to-end, 단계별 *_ms 는 Spring 내부 구간 측정.
CREATE TABLE response_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    issue_key VARCHAR(255),
    slack_user_id VARCHAR(255),
    slack_channel VARCHAR(255),
    success BOOLEAN NOT NULL,
    total_ms BIGINT NOT NULL,
    classify_ms BIGINT,
    duplicate_ms BIGINT,
    jira_ms BIGINT,
    db_ms BIGINT,
    notify_ms BIGINT,
    error_type VARCHAR(255),
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_response_metrics_started_at ON response_metrics (started_at);
