-- v0.0.32: 대시보드 기능요청 게시판. 등록 시 관리자에게 Slack DM, 구현 후 완료 처리.
CREATE TABLE feature_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    author VARCHAR(255),
    done BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX idx_feature_requests_created_at ON feature_requests (created_at);
