-- v0.0.39: GitHub 로그인 → Jira 사용자 매핑. PR import 가 PR 작성자를 보고자/담당자로 정확히 지정하기 위함.
-- GitHub 프로필 이름이 Jira displayName 과 다른 경우(한글팀: 로그인≠영문 표시명)를 명시 매핑으로 해결.
CREATE TABLE github_user_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_login VARCHAR(255) NOT NULL,
    jira_account_id VARCHAR(255) NOT NULL,
    jira_display_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_github_user_mappings_login UNIQUE (github_login)
);
