-- v0.0.71: 공개 HTML 아티팩트 갤러리. html 은 TEXT(최대 5MB, 서버 검증) — 파일시스템 대신 DB 저장
-- (재배포에도 유지, 기존 볼륨/백업에 포함). 뷰어(/artifacts/view/{id})는 무인증 공개.
CREATE TABLE artifacts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200) NOT NULL,
    author     VARCHAR(100),
    html       TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_artifacts_created_at ON artifacts (created_at);
