-- v0.0.72: 아티팩트 자산 (저장된 웹페이지의 page_files/ 등 상대 참조 파일).
-- 조회는 (artifact_id, path) 정확 일치 — UNIQUE 제약의 btree 인덱스가
-- artifact_id 단독 조회(목록 assetCount 서브쿼리)도 커버하므로 별도 인덱스 불필요.
CREATE TABLE artifact_assets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id  BIGINT       NOT NULL REFERENCES artifacts (id) ON DELETE CASCADE,
    path         VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    data         BYTEA        NOT NULL,
    CONSTRAINT uq_artifact_assets_artifact_path UNIQUE (artifact_id, path)
);
