-- v0.0.75: 아티팩트 인라인 댓글 (Google Docs 스타일). 앵커는 W3C TextQuoteSelector
-- (quote + prefix/suffix ~32자) — HTML 수정(PUT) 후 못 찾으면 사이드바에 '위치 없음'으로 잔존.
-- 대댓글은 parent_id 자기참조 (1단계만, 앵커 필드 NULL — 루트의 앵커를 상속).
CREATE TABLE artifact_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_id BIGINT       NOT NULL REFERENCES artifacts (id) ON DELETE CASCADE,
    parent_id   BIGINT       REFERENCES artifact_comments (id) ON DELETE CASCADE,
    author      VARCHAR(100),
    body        TEXT         NOT NULL,
    quote       TEXT,
    prefix      VARCHAR(64),
    suffix      VARCHAR(64),
    resolved    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_artifact_comments_artifact ON artifact_comments (artifact_id);
-- parent_id 인덱스: 자기참조 FK 의 CASCADE 삭제가 자식 스캔을 하므로 필요.
CREATE INDEX idx_artifact_comments_parent ON artifact_comments (parent_id);
