-- v0.0.79: 대시보드 사용자 계정 (관리자가 직접 생성). 관리자(sol)는 .env 로 관리하고 여기 저장하지 않는다.
-- password_hash 는 DelegatingPasswordEncoder 형식 그대로 저장 ("{bcrypt}$2a$10$..." — 길이 ~68).
CREATE TABLE dashboard_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)  NOT NULL UNIQUE,
    display_name  VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
